from Hinata import HOKAGE_ID, GENINS, ACADEMY_USERS, JONINS, CHUNINS, telethn

IMMUNE_USERS = JONINS + ACADEMY_USERS + CHUNINS + GENINS + HOKAGE_ID

IMMUNE_USERS = (
    list(JONINS) + list(ACADEMY_USERS) + list(CHUNINS) + list(GENINS) + list(HOKAGE_ID)
)
