from Hinata import DEV_USERS, GENINS, ACADEMY_USERS, JONINS, CHUNINS, telethn

IMMUNE_USERS = JONINS + ACADEMY_USERS + CHUNINS + GENINS + DEV_USERS

IMMUNE_USERS = (
    list(JONINS) + list(ACADEMY_USERS) + list(CHUNINS) + list(GENINS) + list(DEV_USERS)
)
